security/mainapp/urls.py
from django.urls import path
from mainapp.views import MainListView, CertificateListView, ContactListView

app_name = 'mainapp'

urlpatterns = [
    path('', MainListView.as_view(), name='index'),
    path('certificate/', CertificateListView.as_view(), name='certificate'),
    path('contact/', ContactListView.as_view(), name='contact'),
]

security/security/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
]

security/mainapp/models.py
from django.db import models

# Create your models here.

security/mainapp/views.py
from django.contrib.auth.models import User
from django.views.generic import ListView, View


class MainListView(ListView):
    model = User
    template_name = 'mainapp/index.html'


class CertificateListView(ListView):
    model = User
    template_name = 'mainapp/certificate.html'


class ContactListView(ListView):
    model = User
    template_name = 'mainapp/contact.html'

security/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Щит и Меч</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free Website Template" name="keywords">
    <meta content="Free Website Template" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.jpg' %}" rel="icon">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap"
          rel="stylesheet">
     <link href="{% static 'fonts/stylesheet.css' %}" rel="stylesheet" type="text/css" />
     <link href="{% static 'fonts/Kianda.woff' %}" rel="stylesheet" type="text/css" />

    <!-- CSS Libraries -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!-- Top Bar Start -->
<div class="top-bar d-none d-md-block">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="top-bar-left">
                    <div class="text">
                        <h2>9:00 - 17:00</h2>
                        <p>Режим работы Пн - Пт</p>
                        <p>Обед 13:00 - 14:00</p>
                    </div>
                    <div class="text">
                        <h2>8(38822) 2-06-05</h2>
                        <p>Свяжитесь с нами</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="top-bar-right">
                    <div class="social">
                        <a href=""><i class="fab fa-vk"></i></a>
                        <a href=""><i class="fab fa-facebook-f"></i></a>
                        <a href=""><i class="fab fa-whatsapp"></i></a>
                        <a href=""><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'mainapp/include/inc_menu.html'%}

{% block 'content' %}
{% endblock %}


<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="row">
                    <div class="col-md-6">
                        <div class="footer-contact">
                            <h2>Адрес</h2>
                            <p><i class="fa fa-map-marker"></i>649000, Республика Алтай, г Горно-Алтайск, ул Кучияк д 7</p>
                            <p><i class="fa fa-phone"></i>8(38822) 2-06-05</p>
                            <p><i class="fa fa-envelope"></i>mech727@yandex.ru</p>
                            <div class="footer-social">
                                <a href=""><i class="fab fa-vk"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-whatsapp"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-link">
                            <h2>Ссылки</h2>
                            <a href="">О нас</a>
                            <a href="">Сертификаты</a>
                            <a href="">Услуги</a>
                            <a href="">Цены</a>
                            <a href="">Часто задаваемые вопросы</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

security/mainapp/templates/mainapp/certificate.html
{% extends 'mainapp/base.html'%}
{% load static %}

{% block 'content' %}

<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Сертификаты</h2>
            </div>
            <div class="col-12">
                <a href="{% url 'mainapp:index' %}">Главная</a>
                <a href="{% url 'mainapp:certificate' %}">Сертификаты</a>
            </div>
        </div>
    </div>
</div>


<div class="price">
    <div class="container">
        <div class="section-header text-center">
            <p>Вы можете скачать и ознакомиться с любым из представленных документов</p>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="price-item">
                    <i class="fa fa-book fa-3x" aria-hidden="true"></i>
                    <div class="price-text">
                        <h2 class="fs-14">Устав</h2>
                        <h3><a href="{% static 'docs/regulation.pdf' %}" download="" class="readmore">Скачать</a></h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="price-item">
                    <i class="fa fa-address-card-o fa-3x" aria-hidden="true"></i>
                    <div class="price-text">
                        <h2 class="fs-14">Членство<br> в ФКЦ</h2>
                        <h3><a href="{% static 'docs/participation.pdf' %}" download="" class="readmore">Скачать</a></h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="price-item">
                    <i class="fa fa-check-circle-o fa-3x" aria-hidden="true"></i>
                    <div class="price-text">
                        <h2 class="fs-14">Лицензия</h2>
                        <h3><a href="{% static 'docs/license.pdf' %}" download="" class="readmore">Скачать</a></h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="price-item">
                    <i class="fa fa-pencil-square-o fa-3x" aria-hidden="true"></i>
                    <div class="price-text">
                        <h2 class="fs-14">Выписка из реестра<br> лицензий</h2>
                        <h3><a href="{% static 'docs/license_registry.pdf' %}" download="" class="readmore">Скачать</a></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

security/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html'%}
{% load static %}

{% block 'content' %}

<div class="page-header contact-back">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Контакты</h2>
            </div>
            <div class="col-12">
                <a href="{% url 'mainapp:index' %}">Главная</a>
                <a href="{% url 'mainapp:contact' %}">Контакты</a>
            </div>
        </div>
    </div>
</div>

<div class="section-header text-center" style="margin-top: 90px;">
    <p>Мы постараемся ответить на любые Ваши вопросы</p>
    <h2>Вы можете писать нам в любое время</h2>
</div>
<div class="d-flex">
    <div class="contact-cards"><p class="height-contact" style="padding-top: 24px;"><i class="fa fa-map-marker fa-2x"></i>649000, Республика Алтай, г Горно-Алтайск, ул Кучияк д 7</p></div>
    <div class="contact-cards"><p class="height-contact" style="padding: 24px 0;"><i class="fa fa-phone fa-2x"></i>8(38822) 2-06-05</p></div>
    <div class="contact-cards"> <p class="height-contact" style="padding: 24px 0;"><i class="fa fa-envelope fa-2x"></i>mech727@yandex.ru</p></div>
</div>
<div class="contact">
    <div>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div style="position:relative;overflow:hidden;"><a href="https://yandex.ru/maps/11319/gorno-altaysk/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Горно‑Алтайск</a><a href="https://yandex.ru/maps/11319/gorno-altaysk/house/ulitsa_pavla_kuchiyak_7/bEwYfwFmTE0GQFtrfXV3cXhlbA==/?ll=85.966581%2C51.960468&utm_medium=mapframe&utm_source=maps&z=16.33" style="color:#eee;font-size:12px;position:absolute;top:14px;">Улица Павла Кучияк, 7 — Яндекс Карты</a><iframe src="https://yandex.ru/map-widget/v1/?ll=85.966581%2C51.960468&mode=search&ol=geo&ouri=ymapsbm1%3A%2F%2Fgeo%3Fdata%3DCgoxOTQzMTQ4MzIxEm_QoNC-0YHRgdC40Y8sINCg0LXRgdC_0YPQsdC70LjQutCwINCQ0LvRgtCw0LksINCT0L7RgNC90L4t0JDQu9GC0LDQudGB0LosINGD0LvQuNGG0LAg0J_QsNCy0LvQsCDQmtGD0YfQuNGP0LosIDciCg3j7qtCFYXXT0I%2C&z=16.33" width="560" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>
                </div>
                <div class="col-md-6">
                    <div class="contact-form">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="control-group">
                                <input type="text" class="form-control" id="name" placeholder="Ваше Имя"
                                       required="required" data-validation-required-message="Введите Ваше имя"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" class="form-control" id="email" placeholder="Email"
                                       required="required" data-validation-required-message="Введите ваш email"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control" id="subject" placeholder="Тема"
                                       required="required" data-validation-required-message="Введите тему письма"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control" id="message" placeholder="Сообщение" required="required"
                                          data-validation-required-message="Введите сообщение"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn" type="submit" id="sendMessageButton">Отправить письмо</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

security/mainapp/templates/mainapp/include/inc_menu.html
{% load static %}
<div class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <a href="{% url 'mainapp:index' %}" class="navbar-brand"><img src="{% static 'img/main-safe.png' %}"></a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav ml-auto">
                <a href="{% url 'mainapp:index' %}" class="nav-item nav-link {% if request.resolver_match.view_name == 'mainapp:index'%} active {% endif %}">Главная</a>
                <a href="about.html" class="nav-item nav-link">О нас</a>
                <a href="service.html" class="nav-item nav-link">Услуги</a>
                <a href="price.html" class="nav-item nav-link">Цены</a>
                <a href="{% url 'mainapp:certificate' %}" class="nav-item nav-link {% if request.resolver_match.view_name == 'mainapp:certificate'%} active {% endif %}">Сертификаты</a>
                <a href="{% url 'mainapp:contact' %}" class="nav-item nav-link {% if request.resolver_match.view_name == 'mainapp:contact'%} active {% endif %}">Контакты</a>
            </div>
        </div>
    </div>
</div>

security/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}
{% load static %}

{% block 'content' %}
<div class="hero">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="hero-text">
                    <img src="{% static 'img/mech.png' %}" style="width: 70%;">
                    <p>
                        АВТОНОМНАЯ НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ ДОПОЛНИТЕЛЬНОГО ПРОФЕССИОНАЛЬНОГО ОБРАЗОВАНИЯ И ПРАВОВОГО
                        ПРОСВЕЩЕНИЯ В ОБЛАСТИ ПРАВА И ЧАСТНОЙ ОХРАННОЙ ДЕЯТЕЛЬНОСТИ
                    </p>
                    <span>Основано в 2017 г.</span>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 d-none d-md-block">
                <div class="hero-image">
                    <img src="{% static 'img/weahpon.jpg' %}" alt="Hero Image">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="about">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="about-img">
                    <img src="{% static 'img/about-us.jpg' %}" alt="Image">
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="section-header text-left">
                    <h2>О нас</h2>
                </div>
                <div class="about-text">
                    <p>
                        АНО ДПО ПП ЧОД «ЩИТ И МЕЧ» на основании Лицензии № Л035-01264-04/00174124 от 25.08.201,
                        осуществляет образовательную деятельность по подготовке частных охранников по согласованным с
                        Росгвардией программам дополнительного профессионального обучения.

                    </p>
                    <p>
                        АНО ДПО ПП ЧОД «ЩИТ И МЕЧ» является членом ФКЦ
                        РОС(Федеральный координационный центр руководителей охранных структур), членом ФКЦ РООР
                        Республики Алтай, ведет деятельность в области правового просвещения, соответственно понимает
                        насколько нужна и важна подготовка кадров для охранных структур.
                    </p>
                    <div class="FAQ" style="">
                        <a href="#hide2" class="hide btn" id="hide2">Узнать подробнее</a>
                        <div class="list">
                            <p>
                                Услуги: повышение квалификации частным охранникам 4, 5 и 6 разрядов, что актуально для
                                продления срока действия удостоверения (это регламентируется Приказом МВД РФ от 29
                                сентября 2011 г., № 1039).
                                Дополнительно осуществляет образовательную деятельность по повышению квалификации
                                представителей руководящего состава частных охранных структур – директоров ЧОО.
                                Порядок поступления на обучение:
                                Прием обучающихся в группу происходит на договорной основе, на основании заявления на
                                имя директора (АНО ДПО ПП ЧОД «ЩИТ И МЕЧ»), с предоставлением анкетных данных.
                                Зачисленные приказом директора учреждения в группу обучающиеся, проходят обучение, в
                                соответствии с планом утвержденных учебных программ сдают экзамены, зачеты, проходят
                                промежуточную и итоговую аттестацию в форме квалификационного экзамена и получают
                                свидетельства установленного образца.
                                АНО ДПО ПП ЧОД «ЩИТ И МЕЧ»– имеет свою материально-техническую базу для подготовки
                                сотрудников охраны.
                            </p>
                        </div>
                        <a href="#show2" class="show btn default-show" id="show2">Скрыть</a>
                        <div class="question"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="banner">
    <div class="banner-item back-beige">
        <img class="banner-img" src="{% static 'img/schedue.png' %}" alt="Image">
        <h1 class="top-len">Оптимальный график посещения</h1>
        <p class="color-red descr-p">Обучение проходит в удобное для вас время:<br> с отрывом и без отрыва от трудовой
            деятельности</p>
    </div>
    <div class="banner-item back-red">
        <img class="banner-img" src="{% static 'img/experience.png' %}" alt="Image">
        <h1 class="top-len color-beige">Опыт обучения более 15 лет</h1>
        <p class="color-beige descr-p">Занятия в Центре проводят педагоги с большим опытом практической
            деятельности</p>
    </div>
    <div class="banner-item back-beige">
        <img class="banner-img" src="{% static 'img/location.png' %}" alt="Image">
        <h1 class="top-len">Удобное месторасположение</h1>
        <p class="color-red descr-p">649000, Республика&nbsp;Алтай,<br> г.Горно-Алтайск, ул.Кучияк, д.7</p>
    </div>
    <div class="banner-item back-red">
        <img class="banner-img" src="{% static 'img/quality.png' %}" alt="Image">
        <h1 class="top-len color-beige">Качественное обучение</h1>
        <p class="color-beige descr-p">Разработанные программы, соответствуют всем современным стандартам</p>
    </div>
</div>


<div class="service">
    <div class="container">
        <div class="section-header text-center">
            <h2>Наши услуги</h2>
            <p>ПЛАТНЫЕ ОБРАЗОВАТЕЛЬНЫЕ УСЛУГИ</p>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="service-item">
                    <div class="service-img">
                        <img src="{% static 'img/privat.jpg' %}" alt="Image">
                    </div>
                    <h3 class="height-h">Повышение квалификации частным охранникам</h3>
                    <p class="height-p">
                        Актуально для продления срока действия удостоверения
                        (это регламентируется Приказом МВД РФ от 29 сентября 2011 г., № 1039)
                    </p>
                    <a class="btn" href="">Узнать больше</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="service-item">
                    <div class="service-img">
                        <img src="{% static 'img/boss.jpg' %}" alt="Image">
                    </div>
                    <h3 class="height-h">Повышение квалификации представителей руководящего состава </h3>
                    <p class="height-p">
                        Дополнительно осуществляет образовательную деятельность по повышению
                        квалификации представителей руководящего состава частных охранных структур – директоров ЧОО
                    </p>
                    <a class="btn" href="">Узнать больше</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="service-item">
                    <div class="service-img">
                        <img src="{% static 'img/others.jpg' %}" alt="Image">
                    </div>
                    <h3 class="height-h">Другие услуги</h3>
                    <p class="height-p">
                        Предоставление материально-технической базы для прохождения охранниками обязательной
                        ПЕРИОДИЧЕСКОЙ ПРОВЕРКИ
                    </p>
                    <a class="btn" href="">Узнать больше</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="contact">
    <div class="container-fluid">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4"></div>
                <div class="col-md-8">
                    <div class="contact-form">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="control-group">
                                <input type="text" class="form-control" id="name" placeholder="Ваше Имя"
                                       required="required" data-validation-required-message="Введите Ваше имя"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" class="form-control" id="email" placeholder="Email"
                                       required="required" data-validation-required-message="Введите ваш email"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control" id="subject" placeholder="Тема"
                                       required="required" data-validation-required-message="Введите тему письма"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control" id="message" placeholder="Сообщение" required="required"
                                          data-validation-required-message="Введите сообщение"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn" type="submit" id="sendMessageButton">Отправить письмо</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}